In [ ]:
import json
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

# ----------------------------
# 1. 连接数据库
# ----------------------------
engine = create_engine("postgresql://XXXXXX:YYYYYY@localhost:5432/eyewear-data")

# ----------------------------
# 2. 读取基础数据
# ----------------------------
store_df = pd.read_sql("""
    SELECT
        s.store_id,
        s.store_name,
        s.store_region,
        s.store_city,
        s.store_country,
        s.store_opening_date,
        s.store_type
    FROM "StoreInfo" s
""", engine)

sales_df = pd.read_sql("""
    SELECT
        o.store_id,
        SUM(oi.quantity) AS total_qty,
        ROUND(COALESCE(SUM(oi.line_price_after_tax), 0), 2) AS total_revenue,
        COUNT(DISTINCT o.order_id) AS order_count,
        COUNT(DISTINCT o.customer_id) AS customer_count,
        ROUND(COALESCE(AVG(oi.line_price_after_tax), 0), 2) AS avg_line_revenue
    FROM "OrderItem" oi
    LEFT JOIN "Order" o ON o.order_id = oi.order_id
    GROUP BY o.store_id
""", engine)

# 该门店的主力产品/品牌结构，便于写“门店简报”
product_mix_df = pd.read_sql("""
    SELECT
        o.store_id,
        p.category,
        p.sub_category,
        p.brand,
        SUM(oi.quantity) AS qty,
        ROUND(COALESCE(SUM(oi.line_price_after_tax), 0), 2) AS revenue
    FROM "OrderItem" oi
    LEFT JOIN "Order" o ON o.order_id = oi.order_id
    LEFT JOIN "ProductInfo" p ON p.product_id = oi.product_id
    GROUP BY o.store_id, p.category, p.sub_category, p.brand
""", engine)

# 兜底：避免空值导致后续排序出问题
sales_df["total_qty"] = sales_df["total_qty"].fillna(0)
sales_df["total_revenue"] = sales_df["total_revenue"].fillna(0)
sales_df["order_count"] = sales_df["order_count"].fillna(0)
sales_df["customer_count"] = sales_df["customer_count"].fillna(0)
sales_df["avg_line_revenue"] = sales_df["avg_line_revenue"].fillna(0)

# ----------------------------
# 3. 门店主力产品结构辅助函数
# ----------------------------
def top_store_mix(store_id, top_n=3):
    g = product_mix_df[product_mix_df["store_id"] == store_id].copy()
    if g.empty:
        return "暂无产品结构数据"
    g = g.sort_values(["revenue", "qty"], ascending=False).head(top_n)
    mix = []
    for _, row in g.iterrows():
        brand = row["brand"] or "未知品牌"
        category = row["category"] or "未知类目"
        revenue = row["revenue"] or 0
        mix.append(f"{brand}/{category}({round(float(revenue), 0)}元)")
    return "；".join(mix)

# ----------------------------
# 4. 合并门店基本信息 + 销售聚合
# ----------------------------
df = store_df.merge(sales_df, on="store_id", how="left")
df

,store_id,store_name,store_region,store_city,store_country,store_opening_date,store_type,total_qty,total_revenue,order_count,customer_count,avg_line_revenue
0,1,Ray-Ban La Jolla,California,La Jolla,United States,2002-08-12,Ray-Ban Store,10379,2731434.04,6235,4595,296.67
1,2,Ray-Ban San Diego,California,San Diego,United States,2020-08-20,Ray-Ban Store,24965,6606626.95,15187,8581,295.97
2,3,Ray-Ban Santa Clara,California,Santa Clara,United States,2015-09-14,Ray-Ban Store,19498,5171752.08,11901,7156,296.19
3,4,Ray-Ban Malibu,California,Malibu,United States,2019-09-29,Ray-Ban Store,13420,3544674.34,8130,6277,293.19
4,5,Ray-Ban Newport Beach,California,Newport Beach,United States,2021-07-06,Ray-Ban Store,18145,4837599.60,10874,7565,300.79
...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,LensCrafters North State Street,Illinois,Chicago,United States,2016-10-26,Multi-brand Retail,7000,1847179.01,4241,3858,295.83
97,98,LensCrafters 1055 W Bryn Mawr,Illinois,Chicago,United States,2022-01-09,Multi-brand Retail,7001,1847425.79,4252,3880,291.71
98,99,LensCrafters Macy's - State Street,Illinois,Chicago,United States,2018-07-10,Multi-brand Retail,7025,1873960.44,4212,3855,299.88
99,100,LensCrafters Oakbrook Center Mall,Illinois,Oak Brook,United States,2007-08-23,Multi-brand Retail,5883,1570648.44,3608,2780,298.72
100,101,LensCrafters Macy's - Oakbrook,Illinois,Oak Brook,United States,2016-02-26,Multi-brand Retail,5941,1562277.19,3643,2839,293.77

In [2]:

# 排名：相对全门店做比较
df["revenue_rank"] = df["total_revenue"].rank(method="min", ascending=False).astype("Int64")
df["qty_rank"] = df["total_qty"].rank(method="min", ascending=False).astype("Int64")
df

,store_id,store_name,store_region,store_city,store_country,store_opening_date,store_type,total_qty,total_revenue,order_count,customer_count,avg_line_revenue,revenue_rank,qty_rank
0,1,Ray-Ban La Jolla,California,La Jolla,United States,2002-08-12,Ray-Ban Store,10379,2731434.04,6235,4595,296.67,21,20
1,2,Ray-Ban San Diego,California,San Diego,United States,2020-08-20,Ray-Ban Store,24965,6606626.95,15187,8581,295.97,4,4
2,3,Ray-Ban Santa Clara,California,Santa Clara,United States,2015-09-14,Ray-Ban Store,19498,5171752.08,11901,7156,296.19,6,6
3,4,Ray-Ban Malibu,California,Malibu,United States,2019-09-29,Ray-Ban Store,13420,3544674.34,8130,6277,293.19,13,13
4,5,Ray-Ban Newport Beach,California,Newport Beach,United States,2021-07-06,Ray-Ban Store,18145,4837599.60,10874,7565,300.79,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,LensCrafters North State Street,Illinois,Chicago,United States,2016-10-26,Multi-brand Retail,7000,1847179.01,4241,3858,295.83,49,49
97,98,LensCrafters 1055 W Bryn Mawr,Illinois,Chicago,United States,2022-01-09,Multi-brand Retail,7001,1847425.79,4252,3880,291.71,48,48
98,99,LensCrafters Macy's - State Street,Illinois,Chicago,United States,2018-07-10,Multi-brand Retail,7025,1873960.44,4212,3855,299.88,46,47
99,100,LensCrafters Oakbrook Center Mall,Illinois,Oak Brook,United States,2007-08-23,Multi-brand Retail,5883,1570648.44,3608,2780,298.72,57,58
100,101,LensCrafters Macy's - Oakbrook,Illinois,Oak Brook,United States,2016-02-26,Multi-brand Retail,5941,1562277.19,3643,2839,293.77,58,57

In [ ]:

# ----------------------------
# 5. 生成门店知识卡片
# ----------------------------
def safe_num(x, digits=2):
    if pd.isna(x):
        return "—"
    return round(float(x), digits)

def generate_store_card(row):
    store_name = row["store_name"] or "未知门店"
    store_region = row["store_region"] or "未知地区"
    store_city = row["store_city"] or "未知城市"
    store_country = row["store_country"] or "未知国家"
    store_type = row["store_type"] or "未知类型"
    opening_date = row["store_opening_date"] or "未知开业时间"

    total_qty = safe_num(row["total_qty"], digits=0)
    total_revenue = safe_num(row["total_revenue"], digits=0)
    order_count = safe_num(row["order_count"], digits=0)
    customer_count = safe_num(row["customer_count"], digits=0)
    avg_line_revenue = safe_num(row["avg_line_revenue"], digits=0)

    revenue_rank = row["revenue_rank"]
    qty_rank = row["qty_rank"]
    store_mix = top_store_mix(row["store_id"], top_n=3)

    if pd.notna(revenue_rank) and revenue_rank <= 10:
        performance_signal = f"门店销售表现位居全网第{int(revenue_rank)}名，属于高表现门店"
    elif pd.notna(revenue_rank) and revenue_rank <= 30:
        performance_signal = "门店销售表现处于中上水平，具备稳定增长潜力"
    else:
        performance_signal = "门店表现处于行业均值水平，仍有提升空间"

    revenue_rank_text = int(revenue_rank) if pd.notna(revenue_rank) else "—"
    qty_rank_text = int(qty_rank) if pd.notna(qty_rank) else "—"

    card = (
        f"门店名称：{store_name}。"
        f"门店定位：{store_country} {store_region} {store_city}，门店类型：{store_type}，开业时间：{opening_date}。"
        f"门店累计销售：{total_qty}件，销售额¥{total_revenue}，成交订单{order_count}单，覆盖顾客{customer_count}人，客单价约¥{avg_line_revenue}。"
        f"门店结构：{store_mix}。"
        f"经营判断：{performance_signal}；按销售额排名看，门店约位于第{revenue_rank_text}位，按销量排名看，门店约位于第{qty_rank_text}位。"
        f"综合判断：该门店在{store_region}市场中具备明显经营优势，适合围绕{store_mix.split('；')[0]}等主力产品组合持续加大营销和陈列，"
        f"同时关注{store_city}本地客群的复购节奏和高客单品类提升。"
    )
    return card

df["knowledge_card"] = df.apply(generate_store_card, axis=1)

# ----------------------------
# 6. 导出
# ----------------------------
output = df[[
    "store_id",
    "store_name",
    "store_region",
    "store_city",
    "store_country",
    "store_type",
    "total_qty",
    "total_revenue",
    "order_count",
    "customer_count",
    "avg_line_revenue",
    "knowledge_card"
]].copy()

# 导出 JSONL（适合 RAG / LLM）
path = r".\7-RAG+LLM"
records = output.to_dict(orient="records")
with open(f"{path}/output/7-5-store_knowledge_cards.jsonl", "w", encoding="utf-8-sig", newline="") as f:
    for row in records:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

# # 导出 Parquet（可选，后续分析/检索都方便）
# output.to_parquet("store_knowledge_cards.parquet", index=False)

# 预览
print("已生成门店知识卡片，共", len(output), "家门店")
print(output[["store_name", "knowledge_card"]].head(1).to_string(index=False))

已生成门店知识卡片，共 101 家门店
      store_name                                                                                                                                                                                                                                                                                                                                                                                                                                knowledge_card
Ray-Ban La Jolla 门店名称：Ray-Ban La Jolla。门店定位：United States California La Jolla，门店类型：Ray-Ban Store，开业时间：2002-08-12。门店累计销售：10379.0件，销售额¥2731434.0，成交订单6235.0单，覆盖顾客4595.0人，客单价约¥297.0。门店结构：Ray-Ban/AI Glasses(957576.0元)；Ray-Ban/Sunglasses(713293.0元)；Ray-Ban/Eyeglasses(702294.0元)。经营判断：门店销售表现处于中上水平，具备稳定增长潜力；按销售额排名看，门店约位于第21位，按销量排名看，门店约位于第20位。综合判断：该门店在California市场中具备明显经营优势，适合围绕Ray-Ban/AI Glasses(957576.0元)等主力产品组合持续加大营销和陈列，同时关注La Jolla本地客群的复购节奏和高客单品类提升。